package org.apache.torque.tutorial.om;


/**
 * Maps ResultSet rows into InCorso objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 21 12:08:32 CET 2025]
 *
 */
public class InCorsoRecordMapper extends BaseInCorsoRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1740136112828L;



}
