package org.apache.torque.tutorial.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Feb 21 12:08:32 CET 2025]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class ResoPeer
    extends org.apache.torque.tutorial.om.BaseResoPeer
{

}
