package org.apache.torque.om;


/**
 * Maps ResultSet rows into Corriere objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Mar 04 17:46:16 CET 2025]
 *
 */
public class CorriereRecordMapper extends BaseCorriereRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1741106776310L;



}
