package org.apache.torque.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Mar 04 17:46:15 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class IndirizzoPeerImpl
    extends org.apache.torque.om.BaseIndirizzoPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1741106775335L;



}
