package com.opcal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.torque.Column;
import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.om.mapper.RecordMapper;


/**
 * Maps ResultSet rows into Indirizzo objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Mar 13 14:45:23 CET 2025]
 *
 */
@SuppressWarnings("unused")
public class BaseIndirizzoRecordMapper implements RecordMapper<Indirizzo>
{
    /** Serial version */
    private static final long serialVersionUID = 1741873523084L;

    /** The class log. */
    private static Log log
            = LogFactory.getLog(BaseIndirizzoRecordMapper.class);

    /**
     * Constructs the object from the current row in the resultSet.
     *
     * @param resultSet the resultSet to operate on, already pointing
     *        to the correct row. Not null.
     * @param offset a possible offset in the columns to be considered
     *        (if previous columns contain other objects),
     *        or 0 for no offset.
     * @param criteria The criteria which created the result set.
     *        If set, the attributes to set in the data object
     *        are determined from the select columns in the criteria;
     *        if no matching column can be found, null is returned.
     *        If not set, all of the table's columns are read from the
     *        result set in the order defined in the table definition.
     *
     * @return the mapped object, not null.
     *
     * @throws TorqueException when reading fields from the RecordSet fails
     *         or if a Criteria is passed which contains select columns other
     *         than the columns in the indirizzo table.
     */
    public Indirizzo processRow(
                ResultSet resultSet,
                int offset,
                Criteria criteria)
            throws TorqueException
    {
        Indirizzo indirizzo = new Indirizzo();

        try 
        {
            indirizzo.setLoading(true);
            if (criteria == null)
            {
                indirizzo.setComune(
                        getComune(resultSet, offset + 1));
                indirizzo.setVia(
                        getVia(resultSet, offset + 2));
                indirizzo.setCivico(
                        getCivico(resultSet, offset + 3));
                indirizzo.setOrario(
                        getOrario(resultSet, offset + 4));
                indirizzo.setEmailCliente(
                        getEmailCliente(resultSet, offset + 5));
            }
            else
            {
                // try to get columns to be mapped
                // from criteria's select columns
                boolean columnMapped = false;
                int totalOffset = offset + 1;
                List<Column> selectColumns = criteria.getSelectColumns();
                List<Column> columnsWithoutOffset = selectColumns.subList(
                        offset, 
                        selectColumns.size());
                for (Column column : columnsWithoutOffset)
                {
                    if (BaseIndirizzoPeer.COMUNE.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        indirizzo.setComune(
                            getComune(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseIndirizzoPeer.VIA.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        indirizzo.setVia(
                            getVia(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseIndirizzoPeer.CIVICO.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        indirizzo.setCivico(
                            getCivico(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseIndirizzoPeer.ORARIO.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        indirizzo.setOrario(
                            getOrario(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    else if (BaseIndirizzoPeer.EMAIL_CLIENTE.getSqlExpression().equals(
                            column.getSqlExpression()))
                    {
                        indirizzo.setEmailCliente(
                            getEmailCliente(resultSet, totalOffset));
                        columnMapped = true;
                    }
                    totalOffset++;
                }
                if (!columnMapped)
                {
                    log.debug("no columns to map found in criteria, "
                        + "returning null");
                    return null;
                }
            }
            indirizzo.setNew(false);
            indirizzo.setModified(false);
        }
        finally
        {
            indirizzo.setLoading(false);
        }
        return indirizzo;
    }

    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field comune in Indirizzo.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected String getComune(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getString(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field via in Indirizzo.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected String getVia(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getString(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field civico in Indirizzo.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected String getCivico(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getString(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field orario in Indirizzo.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected int getOrario(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getInt(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }
    /**
     * Reads the value of the <code>columnIndex</code>'th column
     * in the <code>resultSet</code> so that it can be used to set
     * the field emailCliente in Indirizzo.
     *
     * @param resultSet the ResultSet to read from, not null.
     * @param columnIndex the index in the resultSet which should be read.
     *
     * @return the content of the column.
     *
     * @throws SQLException if a problem occurs when reading
     *         from the resultSet.
     */
    protected String getEmailCliente(
                ResultSet resultSet,
                int columnIndex)
            throws TorqueException
    {
        try
        {
            return resultSet.getString(columnIndex);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
    }

}
