package com.opcal;

import java.io.Serializable;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.om.ColumnAccessByName;
import org.apache.torque.util.TorqueConnection;
import org.apache.torque.util.Transaction;

/**
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 13 14:45:21 CET 2025]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to Ricevuta
 */
@SuppressWarnings("unused")
public abstract class BaseRicevuta 
    implements Persistent, Serializable, ColumnAccessByName
{
    /** Serial version */
    private static final long serialVersionUID = 1741873521297L;



    /** Codice della spedizione a cui la ricevuta si riferisce */
    private String codice = null;

    /** Stato del pagamento */
    private String stato = null;

    /** Data del pagamento */
    private java.util.Date data = null;

    /** Cliente a cui la ricevuta è a carico */
    private String emailCliente = null;

    /** Whether this object was modified after loading or after last save. */
    private boolean modified = true;

    /** 
     * Whether this object was loaded from the database or already saved 
     * (false) or whether it is not yet in the database(true).
     */
    private boolean isNew = true;

    /** Flag which indicates whether this object is currently saving. */
    private boolean saving = false;

    /** 
     * Flag which indicates whether this object is currently loaded
     * from the database. 
     */
    private boolean loading = false;

    /** 
     * Flag which indicates whether this object was deleted from the database.
     * Note that this flags does not always display the current database state,
     * there is no magical connection between this flag and the database.
     */
    private boolean deleted = false;

    /** Defines the aCliente field. */
    private Cliente aCliente = null;

    /** Defines the aSpedizione field. */
    private Spedizione aSpedizione = null;





    /**
     * Get the value of codice.
     * The field is described as follows: 
     * Codice della spedizione a cui la ricevuta si riferisce
     *
     * @return the value of codice as String
     */
    public String getCodice() 
    {
        
        return codice;
    }

    /**
     * Set the value of codice.
     * The field is described as follows: 
     * Codice della spedizione a cui la ricevuta si riferisce
     *
     * @param v new value of codice
     */
    public void setCodice(String v)
    {
        if (!Objects.equals(this.codice, v))
        {
            setModified(true);
        }

        this.codice = v;
        if (aSpedizione != null && !Objects.equals(aSpedizione.getCodice(), v))
        {
            aSpedizione = null;
        }


    }
    
    /**
     * Get the value of stato.
     * The field is described as follows: 
     * Stato del pagamento
     *
     * @return the value of stato as String
     */
    public String getStato() 
    {
        
        return stato;
    }

    /**
     * Set the value of stato.
     * The field is described as follows: 
     * Stato del pagamento
     *
     * @param v new value of stato
     */
    public void setStato(String v)
    {
        if (!Objects.equals(this.stato, v))
        {
            setModified(true);
        }

        this.stato = v;


    }
    
    /**
     * Get the value of data.
     * The field is described as follows: 
     * Data del pagamento
     *
     * @return the value of data as java.util.Date
     */
    public java.util.Date getData() 
    {
        
        return data;
    }

    /**
     * Set the value of data.
     * The field is described as follows: 
     * Data del pagamento
     *
     * @param v new value of data
     */
    public void setData(java.util.Date v)
    {
        if (!Objects.equals(this.data, v))
        {
            setModified(true);
        }

        this.data = v;


    }
    
    /**
     * Get the value of emailCliente.
     * The field is described as follows: 
     * Cliente a cui la ricevuta è a carico
     *
     * @return the value of emailCliente as String
     */
    public String getEmailCliente() 
    {
        
        return emailCliente;
    }

    /**
     * Set the value of emailCliente.
     * The field is described as follows: 
     * Cliente a cui la ricevuta è a carico
     *
     * @param v new value of emailCliente
     */
    public void setEmailCliente(String v)
    {
        if (!Objects.equals(this.emailCliente, v))
        {
            setModified(true);
        }

        this.emailCliente = v;
        if (aCliente != null && !Objects.equals(aCliente.getEmail(), v))
        {
            aCliente = null;
        }


    }
    

    /**
     * Returns whether the object has ever been saved.  This will
     * be false, if the object was retrieved from storage or was created
     * and then saved.
     *
     * @return true, if the object has never been persisted.
     */
    public boolean isNew()
    {
        return isNew;
    }

    /**
     * Sets whether the object has ever been saved.
     *
     * @param isNew true if the object has never been saved, false otherwise.
     */
    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }

    /**
     * Returns whether the object has been modified.
     *
     * @return True if the object has been modified.
     */
    public boolean isModified()
    {
        return modified;
    }

    /**
     * Sets whether the object has been modified.
     *
     * @param modified true if the object has been modified, false otherwise.
     */
    public void setModified(boolean modified)
    {
        this.modified = modified;
    }

    /**
     * Sets the modified state for the object to be false.
     */
    public void resetModified()
    {
        modified = false;
    }


    /**
     * Returns whether this object is currently saving.
     *
     * @return true if this object is currently saving, false otherwise.
     */
    public boolean isSaving()
    {
        return saving;
    }

    /**
     * Sets whether this object is currently saving.
     *
     * @param saving true if this object is currently saving, false otherwise.
     */
    public void setSaving(boolean saving)
    {
        this.saving = saving;
    }


    /**
     * Returns whether this object is currently being loaded from the database.
     *
     * @return true if this object is currently loading, false otherwise.
     */
    public boolean isLoading()
    {
        return loading;
    }

    /**
     * Sets whether this object is currently being loaded from the database.
     *
     * @param loading true if this object is currently loading, false otherwise.
     */
    public void setLoading(boolean loading)
    {
        this.loading = loading;
    }


    /**
     * Returns whether this object was deleted from the database.
     * Note that this getter does not automatically reflect database state,
     * it will be set to true by Torque if doDelete() was called with this 
     * object. Bulk deletes and deletes via primary key do not change
     * this flag. Also, if doDelete() was called on an object which does
     * not exist in the database, the deleted flag is set to true even if
     * it was not deleted.
     *
     * @return true if this object was deleted, false otherwise.
     */
    public boolean isDeleted()
    {
        return deleted;
    }

    /**
     * Sets whether this object was deleted from the database.
     *
     * @param deleted true if this object was deleted, false otherwise.
     */
    public void setDeleted(boolean deleted)
    {
        this.deleted = deleted;
    }


    /**
     * Returns the associated Cliente object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Cliente object
     * @throws TorqueException when reading from the database fails.
     */
    public Cliente getCliente()
        throws TorqueException
    {
        if (aCliente == null && !Objects.equals(this.emailCliente, null))
        {
            aCliente = com.opcal.ClientePeer.retrieveByPK(SimpleKey.keyFor(this.emailCliente));
        }
        return aCliente;
    }

    /**
     * Return the associated Cliente object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Cliente object
     * @throws TorqueException If a problem occurs with the get[Cliente] method.
     */
    public Cliente getCliente(Connection connection)
        throws TorqueException
    {
        if (aCliente == null && !Objects.equals(this.emailCliente, null))
        {
            aCliente = com.opcal.ClientePeer.retrieveByPK(SimpleKey.keyFor(this.emailCliente), connection);
        }
        return aCliente;
    }


    /**
     * Declares an association between this object and a Cliente object
     *
     * @param v Cliente
     */
    public void setCliente(Cliente v)
    {
        if (v == null)
        {
            setEmailCliente(null);
        }
        else
        {
            setEmailCliente(v.getEmail());
        }
        aCliente = v;
    }
    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     * @param key the key to set
     * @throws TorqueException if associated objects are not found
     */
    public void setClienteKey(ObjectKey<?> key) throws TorqueException
    {
       
        setEmailCliente(key.toString());
     }

    /**
     * Returns the associated Spedizione object.
     * If it was not retrieved before, the object is retrieved from
     * the database
     *
     * @return the associated Spedizione object
     * @throws TorqueException when reading from the database fails.
     */
    public Spedizione getSpedizione()
        throws TorqueException
    {
        if (aSpedizione == null && !Objects.equals(this.codice, null))
        {
            aSpedizione = com.opcal.SpedizionePeer.retrieveByPK(SimpleKey.keyFor(this.codice));
        }
        return aSpedizione;
    }

    /**
     * Return the associated Spedizione object
     * If it was not retrieved before, the object is retrieved from
     * the database using the passed connection
     *
     * @param connection the connection used to retrieve the associated object
     *        from the database, if it was not retrieved before
     * @return the associated Spedizione object
     * @throws TorqueException If a problem occurs with the get[Spedizione] method.
     */
    public Spedizione getSpedizione(Connection connection)
        throws TorqueException
    {
        if (aSpedizione == null && !Objects.equals(this.codice, null))
        {
            aSpedizione = com.opcal.SpedizionePeer.retrieveByPK(SimpleKey.keyFor(this.codice), connection);
        }
        return aSpedizione;
    }


    /**
     * Declares an association between this object and a Spedizione object
     *
     * @param v Spedizione
     */
    public void setSpedizione(Spedizione v)
    {
        if (v == null)
        {
            setCodice(null);
        }
        else
        {
            setCodice(v.getCodice());
        }
        aSpedizione = v;
    }
    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey, for example
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
     * @param key the key to set
     * @throws TorqueException if associated objects are not found
     */
    public void setSpedizioneKey(ObjectKey<?> key) throws TorqueException
    {
       
        setCodice(key.toString());
     }






    private static final List<String> FIELD_NAMES;

    static
    {
        List<String> fieldNames
                = new ArrayList<String>();
        fieldNames.add("Codice");
        fieldNames.add("Stato");
        fieldNames.add("Data");
        fieldNames.add("EmailCliente");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static List<String> getFieldNames()
    {
        return FIELD_NAMES;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Codice"))
        {
            return getCodice();
        }
        if (name.equals("Stato"))
        {
            return getStato();
        }
        if (name.equals("Data"))
        {
            return getData();
        }
        if (name.equals("EmailCliente"))
        {
            return getEmailCliente();
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Codice"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setCodice((String) value);
            return true;
        }
        if (name.equals("Stato"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setStato((String) value);
            return true;
        }
        if (name.equals("Data"))
        {
            // Object fields can be null
            if (value != null && ! java.util.Date.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setData((java.util.Date) value);
            return true;
        }
        if (name.equals("EmailCliente"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setEmailCliente((String) value);
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (com.opcal.RicevutaPeer.CODICE.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.CODICE.getColumnName().equals(name))
        {
            return getCodice();
        }
        if (com.opcal.RicevutaPeer.STATO.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.STATO.getColumnName().equals(name))
        {
            return getStato();
        }
        if (com.opcal.RicevutaPeer.DATA.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.DATA.getColumnName().equals(name))
        {
            return getData();
        }
        if (com.opcal.RicevutaPeer.EMAIL_CLIENTE.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.EMAIL_CLIENTE.getColumnName().equals(name))
        {
            return getEmailCliente();
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (com.opcal.RicevutaPeer.CODICE.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.CODICE.getColumnName().equals(name))
        {
            return setByName("Codice", value);
        }
        if (com.opcal.RicevutaPeer.STATO.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.STATO.getColumnName().equals(name))
        {
            return setByName("Stato", value);
        }
        if (com.opcal.RicevutaPeer.DATA.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.DATA.getColumnName().equals(name))
        {
            return setByName("Data", value);
        }
        if (com.opcal.RicevutaPeer.EMAIL_CLIENTE.getSqlExpression().equals(name)
            || com.opcal.RicevutaPeer.EMAIL_CLIENTE.getColumnName().equals(name))
        {
            return setByName("EmailCliente", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getCodice();
        }
        if (pos == 1)
        {
            return getStato();
        }
        if (pos == 2)
        {
            return getData();
        }
        if (pos == 3)
        {
            return getEmailCliente();
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("Codice", value);
        }
        if (position == 1)
        {
            return setByName("Stato", value);
        }
        if (position == 2)
        {
            return setByName("Data", value);
        }
        if (position == 3)
        {
            return setByName("EmailCliente", value);
        }
        return false;
    }



    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save() throws TorqueException
    {
        save(RicevutaPeer.DATABASE_NAME);
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param dbName the name of the database to which the object
     *        should be saved.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(String dbName) 
            throws TorqueException
    {
        try (TorqueConnection con = Transaction.begin(dbName))
        {
            save(con);
            Transaction.commit(con);
        }
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally.
     *
     * @param con the connection to use for saving the object, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(Connection con) 
            throws TorqueException
    {
        if (isSaving())
        {
            return;
        }
        try
        {
            setSaving(true);
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    RicevutaPeer.doInsert((Ricevuta) this, con);
                    setNew(false);
                }
                else
                {
                    RicevutaPeer.doUpdate((Ricevuta) this, con);
                }
            }

        }
        finally
        {
            setSaving(false);
        }
    }




    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key codice ObjectKey
     */
    public void setPrimaryKey(ObjectKey<?> key)
        
    {
        setCodice(key.toString());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key the primary key to set.
     */
    public void setPrimaryKey(String key) 
    {
        setCodice(key);
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey<?> getPrimaryKey()
    {
        return SimpleKey.keyFor(getCodice());
    }


    /**
     * Returns an id that differentiates the referenced Cliente object
     * from all other Cliente objects.
     *
     * @return an ObjectKey.
     */
    public ObjectKey<?> getForeignKeyForCliente()
    {
        return SimpleKey.keyFor(getEmailCliente());
    }
    /**
     * Returns an id that differentiates the referenced Spedizione object
     * from all other Spedizione objects.
     *
     * @return an ObjectKey.
     */
    public ObjectKey<?> getForeignKeyForSpedizione()
    {
        return SimpleKey.keyFor(getCodice());
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     * @throws TorqueException if retrieval of the associated objects fails  
     */
    public Ricevuta copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using a connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails     
     */
    public Ricevuta copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Ricevuta copy(boolean deepcopy) throws TorqueException
    {
        Ricevuta ricevuta = new Ricevuta();

        return copyInto(ricevuta, deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Ricevuta copy(boolean deepcopy, Connection con) throws TorqueException
    {
        Ricevuta ricevuta = new Ricevuta();

        return copyInto(ricevuta, deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Ricevuta copyInto(Ricevuta copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Ricevuta copyInto(Ricevuta copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    protected Ricevuta copyInto(Ricevuta copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setCodice((String) null);
        copyObj.setStato(stato);
        copyObj.setData(data);
        copyObj.setEmailCliente(emailCliente);

        if (deepcopy)
        {
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Ricevuta copyInto(Ricevuta copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setCodice((String) null);
        copyObj.setStato(stato);
        copyObj.setData(data);
        copyObj.setEmailCliente(emailCliente);

        if (deepcopy)
        {
        }
        return copyObj;
    }

    /** The Peer class */
    private static final com.opcal.RicevutaPeer peer
            = new com.opcal.RicevutaPeer();

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public com.opcal.RicevutaPeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     * @throws TorqueException if associated objects are not found
     */
    public TableMap getTableMap() throws TorqueException
    {
        return com.opcal.RicevutaPeer.getTableMap();
    }



    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Ricevuta:\n");
        str.append("codice = ")
           .append(getCodice())
           .append("\n");
        str.append("stato = ")
           .append(getStato())
           .append("\n");
        str.append("data = ")
           .append(getData())
           .append("\n");
        str.append("emailCliente = ")
           .append(getEmailCliente())
           .append("\n");
        return(str.toString());
    }

    /**
     * Compares the primary key of this instance with the key of another.
     *
     * @param toCompare The object to compare to.
     * @return Whether the primary keys are equal and the object have the
     *         same class.
     */
    public boolean equals(Object toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!getClass().equals(toCompare.getClass()))
        {
            return false;
        }
        Ricevuta other = (Ricevuta) toCompare;
        if (getPrimaryKey() == null || other.getPrimaryKey() == null)
        {
            return false;
        }
        return getPrimaryKey().equals(other.getPrimaryKey());
    }

    /**
     * If the primary key is not <code>null</code>, return the hashcode of the
     * primary key.  Otherwise calls <code>Object.hashCode()</code>.
     *
     * @return an <code>int</code> value
     */
    public int hashCode()
    {
        ObjectKey<?> ok = getPrimaryKey();
        if (ok == null)
        {
            return super.hashCode();
        }

        return ok.hashCode();
    }



    /**
     * Compares the content of this object to another object
     *
     * @param toCompare The object to compare to.
     * @return true if all of the columns in the other object have 
     *         the same value as the objects in this class.
     */
    public boolean valueEquals(Ricevuta toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!Objects.equals(this.codice, toCompare.getCodice()))
        {
            return false;
        }
        if (!Objects.equals(this.stato, toCompare.getStato()))
        {
            return false;
        }
        if (!Objects.equals(this.data, toCompare.getData()))
        {
            return false;
        }
        if (!Objects.equals(this.emailCliente, toCompare.getEmailCliente()))
        {
            return false;
        }
        return true;
    }



}
