package com.opcal;

import java.io.Serializable;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

import org.apache.torque.TorqueException;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.om.ColumnAccessByName;
import org.apache.torque.criteria.Criteria;
import org.apache.torque.util.TorqueConnection;
import org.apache.torque.util.Transaction;

/**
 * Rubrica corrieri
 *
 * This class was autogenerated by Torque on:
 *
 * [Thu Mar 13 14:45:21 CET 2025]
 *
 * You should not use this class directly.  It should not even be
 * extended; all references should be to Corriere
 */
@SuppressWarnings("unused")
public abstract class BaseCorriere 
    implements Persistent, Serializable, ColumnAccessByName
{
    /** Serial version */
    private static final long serialVersionUID = 1741873521691L;



    /** Partita IVA del corriere */
    private String iva = null;

    /** La ragione sociale del corriere */
    private String nome = null;

    /** Il sito web del corriere */
    private String sito = null;

    /** Il numero di telefono del corriere */
    private String telefono = null;

    /** Il prezzo per spedire 1kg di merce */
    private int prezzo1 = 0;

    /** Il prezzo per spedire 10kg di merce */
    private int prezzo10 = 0;

    /** Il prezzo per spedire 100kg di merce */
    private int prezzo100 = 0;

    /** Whether this object was modified after loading or after last save. */
    private boolean modified = true;

    /** 
     * Whether this object was loaded from the database or already saved 
     * (false) or whether it is not yet in the database(true).
     */
    private boolean isNew = true;

    /** Flag which indicates whether this object is currently saving. */
    private boolean saving = false;

    /** 
     * Flag which indicates whether this object is currently loaded
     * from the database. 
     */
    private boolean loading = false;

    /** 
     * Flag which indicates whether this object was deleted from the database.
     * Note that this flags does not always display the current database state,
     * there is no magical connection between this flag and the database.
     */
    private boolean deleted = false;



    /** Defines the collSpediziones field. */
    protected List<Spedizione> collSpediziones = null;



    /**
     * Get the value of iva.
     * The field is described as follows: 
     * Partita IVA del corriere
     *
     * @return the value of iva as String
     */
    public String getIva() 
    {
        
        return iva;
    }

    /**
     * Set the value of iva.
     * The field is described as follows: 
     * Partita IVA del corriere
     *
     * @param v new value of iva
     */
    public void setIva(String v)
    {
        if (!Objects.equals(this.iva, v))
        {
            setModified(true);
        }

        this.iva = v;

        // update associated objects in collSpediziones 
        if (collSpediziones != null)
        {
            for (Spedizione element : collSpediziones)
            {
                element.setIvaCorriere(v);
            }
        }

    }
    
    /**
     * Get the value of nome.
     * The field is described as follows: 
     * La ragione sociale del corriere
     *
     * @return the value of nome as String
     */
    public String getNome() 
    {
        
        return nome;
    }

    /**
     * Set the value of nome.
     * The field is described as follows: 
     * La ragione sociale del corriere
     *
     * @param v new value of nome
     */
    public void setNome(String v)
    {
        if (!Objects.equals(this.nome, v))
        {
            setModified(true);
        }

        this.nome = v;


    }
    
    /**
     * Get the value of sito.
     * The field is described as follows: 
     * Il sito web del corriere
     *
     * @return the value of sito as String
     */
    public String getSito() 
    {
        
        return sito;
    }

    /**
     * Set the value of sito.
     * The field is described as follows: 
     * Il sito web del corriere
     *
     * @param v new value of sito
     */
    public void setSito(String v)
    {
        if (!Objects.equals(this.sito, v))
        {
            setModified(true);
        }

        this.sito = v;


    }
    
    /**
     * Get the value of telefono.
     * The field is described as follows: 
     * Il numero di telefono del corriere
     *
     * @return the value of telefono as String
     */
    public String getTelefono() 
    {
        
        return telefono;
    }

    /**
     * Set the value of telefono.
     * The field is described as follows: 
     * Il numero di telefono del corriere
     *
     * @param v new value of telefono
     */
    public void setTelefono(String v)
    {
        if (!Objects.equals(this.telefono, v))
        {
            setModified(true);
        }

        this.telefono = v;


    }
    
    /**
     * Get the value of prezzo1.
     * The field is described as follows: 
     * Il prezzo per spedire 1kg di merce
     *
     * @return the value of prezzo1 as int
     */
    public int getPrezzo1() 
    {
        
        return prezzo1;
    }

    /**
     * Set the value of prezzo1.
     * The field is described as follows: 
     * Il prezzo per spedire 1kg di merce
     *
     * @param v new value of prezzo1
     */
    public void setPrezzo1(int v)
    {
        if (this.prezzo1 != v)
        {
            setModified(true);
        }

        this.prezzo1 = v;


    }
    
    /**
     * Get the value of prezzo10.
     * The field is described as follows: 
     * Il prezzo per spedire 10kg di merce
     *
     * @return the value of prezzo10 as int
     */
    public int getPrezzo10() 
    {
        
        return prezzo10;
    }

    /**
     * Set the value of prezzo10.
     * The field is described as follows: 
     * Il prezzo per spedire 10kg di merce
     *
     * @param v new value of prezzo10
     */
    public void setPrezzo10(int v)
    {
        if (this.prezzo10 != v)
        {
            setModified(true);
        }

        this.prezzo10 = v;


    }
    
    /**
     * Get the value of prezzo100.
     * The field is described as follows: 
     * Il prezzo per spedire 100kg di merce
     *
     * @return the value of prezzo100 as int
     */
    public int getPrezzo100() 
    {
        
        return prezzo100;
    }

    /**
     * Set the value of prezzo100.
     * The field is described as follows: 
     * Il prezzo per spedire 100kg di merce
     *
     * @param v new value of prezzo100
     */
    public void setPrezzo100(int v)
    {
        if (this.prezzo100 != v)
        {
            setModified(true);
        }

        this.prezzo100 = v;


    }
    

    /**
     * Returns whether the object has ever been saved.  This will
     * be false, if the object was retrieved from storage or was created
     * and then saved.
     *
     * @return true, if the object has never been persisted.
     */
    public boolean isNew()
    {
        return isNew;
    }

    /**
     * Sets whether the object has ever been saved.
     *
     * @param isNew true if the object has never been saved, false otherwise.
     */
    public void setNew(boolean isNew)
    {
        this.isNew = isNew;
    }

    /**
     * Returns whether the object has been modified.
     *
     * @return True if the object has been modified.
     */
    public boolean isModified()
    {
        return modified;
    }

    /**
     * Sets whether the object has been modified.
     *
     * @param modified true if the object has been modified, false otherwise.
     */
    public void setModified(boolean modified)
    {
        this.modified = modified;
    }

    /**
     * Sets the modified state for the object to be false.
     */
    public void resetModified()
    {
        modified = false;
    }


    /**
     * Returns whether this object is currently saving.
     *
     * @return true if this object is currently saving, false otherwise.
     */
    public boolean isSaving()
    {
        return saving;
    }

    /**
     * Sets whether this object is currently saving.
     *
     * @param saving true if this object is currently saving, false otherwise.
     */
    public void setSaving(boolean saving)
    {
        this.saving = saving;
    }


    /**
     * Returns whether this object is currently being loaded from the database.
     *
     * @return true if this object is currently loading, false otherwise.
     */
    public boolean isLoading()
    {
        return loading;
    }

    /**
     * Sets whether this object is currently being loaded from the database.
     *
     * @param loading true if this object is currently loading, false otherwise.
     */
    public void setLoading(boolean loading)
    {
        this.loading = loading;
    }


    /**
     * Returns whether this object was deleted from the database.
     * Note that this getter does not automatically reflect database state,
     * it will be set to true by Torque if doDelete() was called with this 
     * object. Bulk deletes and deletes via primary key do not change
     * this flag. Also, if doDelete() was called on an object which does
     * not exist in the database, the deleted flag is set to true even if
     * it was not deleted.
     *
     * @return true if this object was deleted, false otherwise.
     */
    public boolean isDeleted()
    {
        return deleted;
    }

    /**
     * Sets whether this object was deleted from the database.
     *
     * @param deleted true if this object was deleted, false otherwise.
     */
    public void setDeleted(boolean deleted)
    {
        this.deleted = deleted;
    }




    /**
     * Initializes the cache collSpediziones for referenced objects.
     * This, means, if collSpediziones is null when this operation is called, it is
     * initialized with an empty collection, otherwise it remains unchanged. 
     *
     * @return the (possibly new) content of the field collSpediziones, not null.
     */
    public List<Spedizione> initSpediziones()
    {
        if (collSpediziones == null)
        {
            collSpediziones = new ArrayList<Spedizione>();
        }
        return collSpediziones;
    }

    /**
     * Checks whether the cache collSpediziones for referenced objects has either been
     * loaded from the database or has been manually initialized.
     *
     * @return boolean true if initialized
     */
    public boolean isSpedizionesInitialized()
    {
        return (collSpediziones != null);
    }


    /**
     * Method called to associate a Spedizione object to this object
     * through the collSpediziones foreign key attribute.
     * If the associated objects were not retrieved before
     * and this object is not new, the associated objects are retrieved
     * from the database before adding the <code>toAdd</code> object.
     *
     * @param toAdd the object to add to the associated objects, not null.
     *
     * @throws TorqueException if retrieval of the associated objects fails.
     * @throws NullPointerException if toAdd is null.
     */
    public void addSpedizione(Spedizione toAdd)
        throws TorqueException
    {
        toAdd.setCorriere((Corriere) this);
        getSpediziones().add(toAdd);
    }

    /**
     * Method called to associate a Spedizione object to this object
     * through the collSpediziones foreign key attribute using connection.
     *
     * @param l Spedizione
     * @throws TorqueException if retrieval of the associated objects fails.
     */
    public void addSpedizione(Spedizione l, Connection con) throws TorqueException
    {
        getSpediziones(con).add(l);
        l.setCorriere((Corriere) this);
    }
    
    /**
     * Method called to reset the cache of Spedizione objects
     * which are related through the collSpediziones foreign key attribute.
     */
    public void resetSpedizione()
    {
        collSpediziones = null;
    }


    /**
     * The criteria used to select the current contents of collSpediziones
     */
    private Criteria lastSpedizioneCriteria = null;

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getSpediziones(new Criteria())
     *
     * @return the collection of associated objects
     * @throws TorqueException
     */
    public List<Spedizione> getSpediziones()
        throws TorqueException
    {
        if (collSpediziones == null)
        {
            collSpediziones = getSpediziones(new Criteria());
            for (Spedizione spedizione : collSpediziones)
            {
                spedizione.setCorriere((Corriere) this);
            }
        }
        return collSpediziones;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere has previously
     * been saved, it will retrieve related collSpediziones from storage.
     * If this BaseCorriere is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     *
     * @throws TorqueException If a problem occurs with the get[criteria] method.     
     */
    public List<Spedizione> getSpediziones(Criteria criteria) throws TorqueException
    {
        if (collSpediziones == null)
        {
            if (isNew())
            {
               initSpediziones();
            }
            else
            {
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                collSpediziones = com.opcal.SpedizionePeer.doSelect(criteria);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        else
        {
            // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                if (lastSpedizioneCriteria == null
                        || !lastSpedizioneCriteria.equals(criteria))
                {
                    collSpediziones = com.opcal.SpedizionePeer.doSelect(criteria);
                    for (Spedizione spedizione : collSpediziones)
                    {
                        spedizione.setCorriere((Corriere) this);
                    }
                }
            }
        }
        lastSpedizioneCriteria = criteria;
        return collSpediziones;
    }

    /**
     * If this collection has already been initialized, returns
     * the collection. Otherwise returns the results of
     * getSpediziones(new Criteria(),Connection)
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<Spedizione> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<Spedizione> getSpediziones(Connection con) throws TorqueException
    {
        if (collSpediziones == null)
        {
            collSpediziones = getSpediziones(new Criteria(), con);
            for (Spedizione spedizione : collSpediziones)
            {
                spedizione.setCorriere((Corriere) this);
            }
        }
        return collSpediziones;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere has previously
     * been saved, it will retrieve the related Spedizione Objects
     * from storage.
     * If this BaseCorriere is new, it will return
     * an empty collection or the current collection, the criteria
     * is ignored on a new object.
     * This method takes in the Connection also as input so that
     * referenced objects can also be obtained using a Connection
     * that is taken as input
     *
     * @param con the Connection
     * @return List<Spedizione> results of the collection
     * @throws TorqueException If a problem occurs with the get[connection] method.
     */
    public List<Spedizione> getSpediziones(Criteria criteria, Connection con)
            throws TorqueException
    {
        if (collSpediziones == null)
        {
            if (isNew())
            {
               initSpediziones();
            }
            else
            {
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                collSpediziones = com.opcal.SpedizionePeer.doSelect(criteria, con);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        else
        {
             // criteria has no effect for a new object
            if (!isNew())
            {
                // the following code is to determine if a new query is
                // called for.  If the criteria is the same as the last
                // one, just return the collection.
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                if (lastSpedizioneCriteria == null
                        || !lastSpedizioneCriteria.equals(criteria))
                {
                    collSpediziones = com.opcal.SpedizionePeer.doSelect(criteria, con);
                    for (Spedizione spedizione : collSpediziones)
                    {
                        spedizione.setCorriere((Corriere) this);
                    }
                }
            }
        }
        lastSpedizioneCriteria = criteria;

        return collSpediziones;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     *
     * @return List<Spedizione> the collection
     * @param criteria the criteria to use when filling the collection.
     * @throws TorqueException if associated objects are not found
     */
    protected List<Spedizione> getSpedizionesJoinClienteRelatedByEmailMittente(Criteria criteria) throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(criteria.getDbName()))
        {
            List<Spedizione> result = getSpedizionesJoinClienteRelatedByEmailMittente(criteria, connection);

            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere is new, it will return
     * an empty collection; or if this BaseCorriere has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Spedizione> getSpedizionesJoinClienteRelatedByEmailMittente(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collSpediziones == null)
        {
            if (isNew())
            {
                initSpediziones();
            }
            else
            {
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                collSpediziones = com.opcal.SpedizionePeer.doSelectJoinClienteRelatedByEmailMittente(criteria, connection);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
            if (lastSpedizioneCriteria == null
                        || !lastSpedizioneCriteria.equals(criteria))
            {
                collSpediziones = com.opcal.SpedizionePeer.doSelectJoinClienteRelatedByEmailMittente(criteria, connection);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        lastSpedizioneCriteria = criteria;

        return collSpediziones;
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere is new, it will return
     * an empty collection; or if this thisObjectClassName has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     *
     * @return List<Spedizione> the collection
     * @param criteria the criteria to use when filling the collection.
     * @throws TorqueException if associated objects are not found
     */
    protected List<Spedizione> getSpedizionesJoinClienteRelatedByEmailDestinatario(Criteria criteria) throws TorqueException
    {
        try (TorqueConnection connection = Transaction.begin(criteria.getDbName()))
        {
            List<Spedizione> result = getSpedizionesJoinClienteRelatedByEmailDestinatario(criteria, connection);

            Transaction.commit(connection);
            return result;
        }
    }

    /**
     * If this collection has already been initialized with
     * an identical criteria, it returns the collection.
     * Otherwise if this BaseCorriere is new, it will return
     * an empty collection; or if this BaseCorriere has previously
     * been saved, it will retrieve the related objects from storage.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can change the access modifier to public
     * by overriding this method in the child class.
     */
    protected List<Spedizione> getSpedizionesJoinClienteRelatedByEmailDestinatario(Criteria criteria, Connection connection)
        throws TorqueException
    {
        if (collSpediziones == null)
        {
            if (isNew())
            {
                initSpediziones();
            }
            else
            {
                criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
                collSpediziones = com.opcal.SpedizionePeer.doSelectJoinClienteRelatedByEmailDestinatario(criteria, connection);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        else
        {
            // the following code is to determine if a new query is
            // called for.  If the criteria is the same as the last
            // one, just return the collection.
            criteria.and(com.opcal.SpedizionePeer.IVA_CORRIERE, getIva());
            if (lastSpedizioneCriteria == null
                        || !lastSpedizioneCriteria.equals(criteria))
            {
                collSpediziones = com.opcal.SpedizionePeer.doSelectJoinClienteRelatedByEmailDestinatario(criteria, connection);
                for (Spedizione spedizione : collSpediziones)
                {
                    spedizione.setCorriere((Corriere) this);
                }
            }
        }
        lastSpedizioneCriteria = criteria;

        return collSpediziones;
    }




    private static final List<String> FIELD_NAMES;

    static
    {
        List<String> fieldNames
                = new ArrayList<String>();
        fieldNames.add("Iva");
        fieldNames.add("Nome");
        fieldNames.add("Sito");
        fieldNames.add("Telefono");
        fieldNames.add("Prezzo1");
        fieldNames.add("Prezzo10");
        fieldNames.add("Prezzo100");
        FIELD_NAMES = Collections.unmodifiableList(fieldNames);
    }

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static List<String> getFieldNames()
    {
        return FIELD_NAMES;
    }

    /**
     * Retrieves a field from the object by field (Java) name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
        if (name.equals("Iva"))
        {
            return getIva();
        }
        if (name.equals("Nome"))
        {
            return getNome();
        }
        if (name.equals("Sito"))
        {
            return getSito();
        }
        if (name.equals("Telefono"))
        {
            return getTelefono();
        }
        if (name.equals("Prezzo1"))
        {
            return Integer.valueOf(getPrezzo1());
        }
        if (name.equals("Prezzo10"))
        {
            return Integer.valueOf(getPrezzo10());
        }
        if (name.equals("Prezzo100"))
        {
            return Integer.valueOf(getPrezzo100());
        }
        return null;
    }

    /**
     * Set a field in the object by field (Java) name.
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (name.equals("Iva"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setIva((String) value);
            return true;
        }
        if (name.equals("Nome"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setNome((String) value);
            return true;
        }
        if (name.equals("Sito"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setSito((String) value);
            return true;
        }
        if (name.equals("Telefono"))
        {
            // Object fields can be null
            if (value != null && ! String.class.isInstance(value))
            {
                throw new IllegalArgumentException("Invalid type of object specified for value in setByName");
            }
            setTelefono((String) value);
            return true;
        }
        if (name.equals("Prezzo1"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setPrezzo1(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Prezzo10"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setPrezzo10(((Integer) value).intValue());
            return true;
        }
        if (name.equals("Prezzo100"))
        {
            if (value == null || ! (Integer.class.isInstance(value)))
            {
                throw new IllegalArgumentException("setByName: value parameter was null or not an Integer object.");
            }
            setPrezzo100(((Integer) value).intValue());
            return true;
        }
        return false;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
        if (com.opcal.CorrierePeer.IVA.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.IVA.getColumnName().equals(name))
        {
            return getIva();
        }
        if (com.opcal.CorrierePeer.NOME.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.NOME.getColumnName().equals(name))
        {
            return getNome();
        }
        if (com.opcal.CorrierePeer.SITO.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.SITO.getColumnName().equals(name))
        {
            return getSito();
        }
        if (com.opcal.CorrierePeer.TELEFONO.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.TELEFONO.getColumnName().equals(name))
        {
            return getTelefono();
        }
        if (com.opcal.CorrierePeer.PREZZO1.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO1.getColumnName().equals(name))
        {
            return Integer.valueOf(getPrezzo1());
        }
        if (com.opcal.CorrierePeer.PREZZO10.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO10.getColumnName().equals(name))
        {
            return Integer.valueOf(getPrezzo10());
        }
        if (com.opcal.CorrierePeer.PREZZO100.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO100.getColumnName().equals(name))
        {
            return Integer.valueOf(getPrezzo100());
        }
        return null;
    }

    /**
     * Set field values by Peer Field Name
     *
     * @param name field name
     * @param value field value
     * @return True if value was set, false if not (invalid name / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPeerName(String name, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (com.opcal.CorrierePeer.IVA.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.IVA.getColumnName().equals(name))
        {
            return setByName("Iva", value);
        }
        if (com.opcal.CorrierePeer.NOME.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.NOME.getColumnName().equals(name))
        {
            return setByName("Nome", value);
        }
        if (com.opcal.CorrierePeer.SITO.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.SITO.getColumnName().equals(name))
        {
            return setByName("Sito", value);
        }
        if (com.opcal.CorrierePeer.TELEFONO.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.TELEFONO.getColumnName().equals(name))
        {
            return setByName("Telefono", value);
        }
        if (com.opcal.CorrierePeer.PREZZO1.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO1.getColumnName().equals(name))
        {
            return setByName("Prezzo1", value);
        }
        if (com.opcal.CorrierePeer.PREZZO10.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO10.getColumnName().equals(name))
        {
            return setByName("Prezzo10", value);
        }
        if (com.opcal.CorrierePeer.PREZZO100.getSqlExpression().equals(name)
            || com.opcal.CorrierePeer.PREZZO100.getColumnName().equals(name))
        {
            return setByName("Prezzo100", value);
        }
        return false;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
        if (pos == 0)
        {
            return getIva();
        }
        if (pos == 1)
        {
            return getNome();
        }
        if (pos == 2)
        {
            return getSito();
        }
        if (pos == 3)
        {
            return getTelefono();
        }
        if (pos == 4)
        {
            return Integer.valueOf(getPrezzo1());
        }
        if (pos == 5)
        {
            return Integer.valueOf(getPrezzo10());
        }
        if (pos == 6)
        {
            return Integer.valueOf(getPrezzo100());
        }
        return null;
    }

    /**
     * Set field values by its position (zero based) in the XML schema.
     *
     * @param position The field position
     * @param value field value
     * @return True if value was set, false if not (invalid position / protected field).
     * @throws IllegalArgumentException if object type of value does not match field object type.
     * @throws TorqueException If a problem occurs with the set[Field] method.
     */
    public boolean setByPosition(int position, Object value)
        throws TorqueException, IllegalArgumentException
    {
        if (position == 0)
        {
            return setByName("Iva", value);
        }
        if (position == 1)
        {
            return setByName("Nome", value);
        }
        if (position == 2)
        {
            return setByName("Sito", value);
        }
        if (position == 3)
        {
            return setByName("Telefono", value);
        }
        if (position == 4)
        {
            return setByName("Prezzo1", value);
        }
        if (position == 5)
        {
            return setByName("Prezzo10", value);
        }
        if (position == 6)
        {
            return setByName("Prezzo100", value);
        }
        return false;
    }



    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save() throws TorqueException
    {
        save(CorrierePeer.DATABASE_NAME);
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.
     *
     * @param dbName the name of the database to which the object
     *        should be saved.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(String dbName) 
            throws TorqueException
    {
        try (TorqueConnection con = Transaction.begin(dbName))
        {
            save(con);
            Transaction.commit(con);
        }
    }

    /**
     * Stores an object in the database.  If the object is new,
     * it is inserted; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally.
     *
     * @param con the connection to use for saving the object, not null.
     *
     * @throws TorqueException if an error occurs during saving.
     */
    public void save(Connection con) 
            throws TorqueException
    {
        if (isSaving())
        {
            return;
        }
        try
        {
            setSaving(true);
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    CorrierePeer.doInsert((Corriere) this, con);
                    setNew(false);
                }
                else
                {
                    CorrierePeer.doUpdate((Corriere) this, con);
                }
            }

            if (isSpedizionesInitialized())
            {
                for (Spedizione collSpediziones : getSpediziones())
                {
                    collSpediziones.save(con);
                }
            }
        }
        finally
        {
            setSaving(false);
        }
    }




    /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key iva ObjectKey
     */
    public void setPrimaryKey(ObjectKey<?> key)
        
    {
        setIva(key.toString());
    }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key the primary key to set.
     */
    public void setPrimaryKey(String key) 
    {
        setIva(key);
    }


    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey<?> getPrimaryKey()
    {
        return SimpleKey.keyFor(getIva());
    }



    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     * @throws TorqueException if retrieval of the associated objects fails  
     */
    public Corriere copy() throws TorqueException
    {
        return copy(true);
    }

    /**
     * Makes a copy of this object using a connection.
     * It creates a new object filling in the simple attributes.
     * It then fills all the association collections and sets the
     * related objects to isNew=true.
     *
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails     
     */
    public Corriere copy(Connection con) throws TorqueException
    {
        return copy(true, con);
    }

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Corriere copy(boolean deepcopy) throws TorqueException
    {
        Corriere corriere = new Corriere();

        return copyInto(corriere, deepcopy);
    }

    /**
     * Makes a copy of this object using connection.
     * It creates a new object filling in the simple attributes.
     * If the parameter deepcopy is true, it then fills all the
     * association collections and sets the related objects to
     * isNew=true.
     *
     * @param deepcopy whether to copy the associated objects.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Corriere copy(boolean deepcopy, Connection con) throws TorqueException
    {
        Corriere corriere = new Corriere();

        return copyInto(corriere, deepcopy, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Corriere copyInto(Corriere copyObj) throws TorqueException
    {
        return copyInto(copyObj, true);
    }

    /**
     * Fills the copyObj with the contents of this object using connection.
     * The associated objects are also copied and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Corriere copyInto(Corriere copyObj, Connection con) throws TorqueException
    {
        return copyInto(copyObj, true, con);
    }
  
    /**
     * Fills the copyObj with the contents of this object.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    protected Corriere copyInto(Corriere copyObj, boolean deepcopy) throws TorqueException
    {
        copyObj.setIva((String) null);
        copyObj.setNome(nome);
        copyObj.setSito(sito);
        copyObj.setTelefono(telefono);
        copyObj.setPrezzo1(prezzo1);
        copyObj.setPrezzo10(prezzo10);
        copyObj.setPrezzo100(prezzo100);

        if (deepcopy)
        {
            if (collSpediziones != null)
            {
                for (Spedizione obj : collSpediziones)
                {
                    copyObj.addSpedizione(obj.copy());
                }
            }
            else
            {
                copyObj.collSpediziones = null;
            }
        }
        return copyObj;
    }
        
    
    /**
     * Fills the copyObj with the contents of this object using connection.
     * If deepcopy is true, The associated objects are also copied
     * and treated as new objects.
     *
     * @param copyObj the object to fill.
     * @param deepcopy whether the associated objects should be copied.
     * @param con the database connection to read associated objects.
     * @throws TorqueException if retrieval of the associated objects fails
     */
    public Corriere copyInto(Corriere copyObj, boolean deepcopy, Connection con) throws TorqueException
    {
        copyObj.setIva((String) null);
        copyObj.setNome(nome);
        copyObj.setSito(sito);
        copyObj.setTelefono(telefono);
        copyObj.setPrezzo1(prezzo1);
        copyObj.setPrezzo10(prezzo10);
        copyObj.setPrezzo100(prezzo100);

        if (deepcopy)
        {
            for (Spedizione obj : getSpediziones(con))
            {
                copyObj.addSpedizione(obj.copy());
            }
        }
        return copyObj;
    }

    /** The Peer class */
    private static final com.opcal.CorrierePeer peer
            = new com.opcal.CorrierePeer();

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public com.opcal.CorrierePeer getPeer()
    {
        return peer;
    }

    /**
     * Retrieves the TableMap object related to this Table data without
     * compiler warnings of using getPeer().getTableMap().
     *
     * @return The associated TableMap object.
     * @throws TorqueException if associated objects are not found
     */
    public TableMap getTableMap() throws TorqueException
    {
        return com.opcal.CorrierePeer.getTableMap();
    }



    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("Corriere:\n");
        str.append("iva = ")
           .append(getIva())
           .append("\n");
        str.append("nome = ")
           .append(getNome())
           .append("\n");
        str.append("sito = ")
           .append(getSito())
           .append("\n");
        str.append("telefono = ")
           .append(getTelefono())
           .append("\n");
        str.append("prezzo1 = ")
           .append(getPrezzo1())
           .append("\n");
        str.append("prezzo10 = ")
           .append(getPrezzo10())
           .append("\n");
        str.append("prezzo100 = ")
           .append(getPrezzo100())
           .append("\n");
        return(str.toString());
    }

    /**
     * Compares the primary key of this instance with the key of another.
     *
     * @param toCompare The object to compare to.
     * @return Whether the primary keys are equal and the object have the
     *         same class.
     */
    public boolean equals(Object toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!getClass().equals(toCompare.getClass()))
        {
            return false;
        }
        Corriere other = (Corriere) toCompare;
        if (getPrimaryKey() == null || other.getPrimaryKey() == null)
        {
            return false;
        }
        return getPrimaryKey().equals(other.getPrimaryKey());
    }

    /**
     * If the primary key is not <code>null</code>, return the hashcode of the
     * primary key.  Otherwise calls <code>Object.hashCode()</code>.
     *
     * @return an <code>int</code> value
     */
    public int hashCode()
    {
        ObjectKey<?> ok = getPrimaryKey();
        if (ok == null)
        {
            return super.hashCode();
        }

        return ok.hashCode();
    }



    /**
     * Compares the content of this object to another object
     *
     * @param toCompare The object to compare to.
     * @return true if all of the columns in the other object have 
     *         the same value as the objects in this class.
     */
    public boolean valueEquals(Corriere toCompare)
    {
        if (toCompare == null)
        {
            return false;
        }
        if (this == toCompare)
        {
            return true;
        }
        if (!Objects.equals(this.iva, toCompare.getIva()))
        {
            return false;
        }
        if (!Objects.equals(this.nome, toCompare.getNome()))
        {
            return false;
        }
        if (!Objects.equals(this.sito, toCompare.getSito()))
        {
            return false;
        }
        if (!Objects.equals(this.telefono, toCompare.getTelefono()))
        {
            return false;
        }
        if (this.prezzo1 != toCompare.getPrezzo1())
        {
            return false;
        }
        if (this.prezzo10 != toCompare.getPrezzo10())
        {
            return false;
        }
        if (this.prezzo100 != toCompare.getPrezzo100())
        {
            return false;
        }
        return true;
    }



}
