package com.opcal;

/**
 * Maps ResultSet rows into Dipendente objects.
 * <p>
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Tue Mar 04 17:46:16 CET 2025]
 */
public class DipendenteRecordMapper extends BaseDipendenteRecordMapper {
  /**
   * Serial version
   */
  private static final long serialVersionUID = 1741106776294L;


}
