package com.opcal;


/**
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Wed Mar 05 18:43:05 CET 2025]
 * <p>
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class Indirizzo
    extends BaseIndirizzo {
  /**
   * Serial version
   */
  private static final long serialVersionUID = 1741196585666L;


}
