package com.opcal;

/**
 * Spedizioni in attesa di ritiro
 * <p>
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Wed Mar 05 18:43:07 CET 2025]
 * <p>
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class PrenotataPeer
    extends BasePrenotataPeer {

}
