package com.opcal;




/**
 * Maps ResultSet rows into Ricevuta objects.
 * <p>
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Wed Mar 05 18:43:08 CET 2025]
 */
public class RicevutaRecordMapper extends BaseRicevutaRecordMapper {
  /**
   * Serial version
   */
  private static final long serialVersionUID = 1741196588259L;


}
