package com.opcal;

/**
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Wed Mar 05 18:43:07 CET 2025]
 * <p>
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class SpedizionePeer
    extends BaseSpedizionePeer {

  public static String[] getFields(){
    return new String[] {"Codice", "Mittente", "Destinatario", "Stato", "Data rilevante", "Peso", "Prezzo", "Corriere"};
  }
}
