package com.opcal;

/**
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Tue Mar 04 17:46:15 CET 2025]
 * <p>
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class UtentePeerImpl
    extends BaseUtentePeerImpl {
  /**
   * Serial version
   */
  private static final long serialVersionUID = 1741106775323L;


}
