package com.opcal;

import org.apache.torque.TorqueException;
import org.apache.torque.criteria.Criteria;

/**
 * The skeleton for this class was autogenerated by Torque on:
 * <p>
 * [Tue Mar 04 17:46:15 CET 2025]
 * <p>
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class UtentePeer
    extends BaseUtentePeer {

  public static Utente cercaUtente(String email, String password) throws TorqueException {
    Criteria criteria = new Criteria();
    criteria.where(UtentePeer.EMAIL, email);
    criteria.where(UtentePeer.PASSWORD, password);
    Utente utente = UtentePeer.doSelect(criteria).getFirst();
    if (utente == null){
      throw new TorqueException("Utente non trovato");
    }
    return utente;
  }
}
