package org.apache.torque.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 27 12:24:17 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class ClientePeerImpl
    extends org.apache.torque.om.BaseClientePeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1740655457597L;



}
