package org.apache.torque.om;

/**
 * Spedizioni in lavorazione
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Mar 05 18:43:07 CET 2025]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class InCorsoPeerImpl
    extends org.apache.torque.om.BaseInCorsoPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1741196587455L;



}
