package org.apache.torque.om;


/**
 * Maps ResultSet rows into InCorso objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Feb 27 12:24:18 CET 2025]
 *
 */
public class InCorsoRecordMapper extends BaseInCorsoRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1740655458076L;



}
