@startuml

left to right direction

actor Cliente
actor Sportellista
actor Portalettere

usecase "Visualizzazione fatture" as UC12
usecase "Ordinamento fatture" as UC11
usecase "Sicurezza login" as UC13
usecase "Visualizzazione stato spedizioni" as UC14
usecase "Visualizzazione stato pagamenti" as UC15
usecase "Accesso dati anagrafici clienti" as UC16
usecase "Modifica dati anagrafici clienti" as UC17
usecase "Accesso dati spedizioni clienti" as UC18
usecase "Modifica dati spedizioni clienti" as UC19
usecase "Sistema di mailing" as UC20
usecase "Per stato di pagamento" as UC21 
usecase "Per data di pagamenteo" as UC22
usecase "In ordine alfabetico" as UC23

Cliente --> UC11
Cliente --> UC12
Cliente --> UC13

Sportellista --> UC13
Sportellista --> UC14
Sportellista --> UC15
Sportellista --> UC16
Sportellista --> UC17
Sportellista --> UC18
Sportellista --> UC19
Sportellista --> UC20
Portalettere --> UC16
Portalettere --> UC18
Portalettere --> UC19

UC16 --> UC17 : <<includes>>
UC18 <-- UC19 : <<extends>>
UC12 --> UC11 : <<include>>

UC11 <-- UC21 :<<extends>>
UC11 <-- UC22 :<<extends>>
UC11 <-- UC23 :<<extends>>




@enduml
